name: Release

on:
  push:
    branches:
      - main

jobs:
  release-npm:
    name: Release to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install --frozen-lockfile --production
      - name: Validate
        run: |
          yarn lint:ci
      - name: Build
        run: |
          yarn build:ci
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
